RUAS = [
    'Avenida Alberto Sanarelli',
    'Avenida Altino Guimarães',
    'Avenida Araponga',
    'Avenida Argentina',
    'Avenida Benedito Romão de Melo',
    'Avenida Brasil',
    'Avenida das Acácias',
    'Avenida das Palmeiras',
    'Avenida Dom Almir Marques',
    'Avenida Dom José André Coimbra',
    'Avenida dos Bálsamos',
    'Avenida dos Jacarandás',
    'Avenida Elias José Abrão',
    'Avenida Enéas Ferreira de Aguiar',
    'Avenida Faria Pereira, 2222',
    'Avenida Faria Pereira',
    'Avenida General Astolfo Ferreira Mendes',
    'Avenida Gentil Rodrigues da Silveira',
    'Avenida Helena Marques Silveira',
    'Avenida Henriqueta Augusta do Carmo',
    'Avenida Jacinto Barbosa',
    'Avenida João Alves do Nascimento',
    'Avenida João Furtado de Oliveira',
    'Avenida Joaquim Constantino',
    'Avenida Joaquim Pedro Barbosa',
    'Avenida Joaquina Marra de Carvalho',
    'Avenida Jorge Elias Abrão',
    'Avenida José Amando Queiroz',
    'Avenida José Elói dos Santos',
    'Avenida José Maria de Alkimim',
    'Avenida Juvelino Ferreira de Souza',
    'Avenida Liria Terezinha Lassi Capuano'
    'Avenida Manuel Nunes',
    'Avenida Marciano Pires',
    'Avenida Minas Gerais',
    'Avenida Odir Aleixo',
    'Avenida Orlando Barbosa',
    'Avenida Padre Caprazio',
    'Avenida Padre Matias',
    'Avenida Pedro Alves do Nascimento',
    'Avenida Pedro Bernardes Dias',
    'Avenida Presidente Juscelino Kubitschek',
    'Avenida Professora Dirce de Ávila Machado',
    'Avenida Rufina Alvina de Jesus',
    'Avenida Rui Barbosa',
    'Avenida Rússia',
    'Avenida Tupinambás',
    'Avenida Venezuela',
    'Avenida Vereador Manoel Carlos de Jesus',
    'Avenida Walter Pereira Nunes',
    'Estrada Municipal PTC-004',
    'Praça Carlos Pierucceti',
    'Praça Honorato Borges',
    'Praça Honorico Nunes Oliveira',
    'Praça Joaquim Tiago',
    'Rua Abadio Marques Nader',
    'Rua Abner Gomes Romão',
    'Rua Adalberto do Nascimento',
    'Rua Adalgisio Dornelas Campos',
    'Rua Adelino Rodrigues da Cunha',
    'Rua Adélio Furtado de Oliveira',
    'Rua Adélio Nunes Caixeta',
    'Rua Adolfo Pieruccetti',
    'Rua Afonsina Silva Amorim',
    'Rua Afonso Alves de Queiroz',
    'Rua Afonso de Paula',
    'Rua Afonso José da Silva',
    'Rua Afonso Paulo Pires',
    'Rua Afonso Pena',
    'Rua Agostinho Machado',
    'Rua Alaíde dos Santos Pinto',
    'Rua Alameda das Acerolas',
    'Rua Alameda das Caviúnas',
    'Rua Alameda das Faveiras',
    'Rua Alameda das Garuvas',
    'Rua Alameda das Goiabas',
    'Rua Alameda das Graviolas',
    'Rua Alameda das Jabuticabas',
    'Rua Alameda das Jaqueiras',
    'Rua Alameda das Maçarandubas',
    'Rua Alameda das Oliveiras',
    'Rua Alameda dos Álamos',
    'Rua Alameda dos Alecrins',
    'Rua Alameda dos Babaçus',
    'Rua Alameda dos Buritis',
    'Rua Alameda dos Carvalhos',
    'Rua Alameda dos Catiguás',
    'Rua Alameda dos Colibris',
    'Rua Alameda dos Cravos',
    'Rua Alameda dos Embarés',
    'Rua Alameda dos Indaiás',
    'Rua Alameda dos Ingás',
    'Rua Alameda dos Paus Brasil',
    'Rua Alameda dos Piquis',
    'Rua Alberto Silva',
    'Rua Aleixo Joaquim de Souza',
    'Rua Alemanha',
    'Rua Alfa Alves de Souza',
    'Rua Alírio Afonso Vieira',
    'Rua Alírio de Melo',
    'Rua Altair Avelos Péres',
    'Rua Altina Leonor de Ávila',
    'Rua Álvares de Azevedo',
    'Rua Amélia Angélica do Nascimento',
    'Rua Amélia Augusta Alves',
    'Rua Amélia Maria da Silva',
    'Rua Amílcar da Costa Romão',
    'Rua Ana Gonçalves dos Santos',
    'Rua Ana Leonor de Paula',
    'Rua Ana Marra',
    'Rua Andorinha',
    'Rua Angela Hooper',
    'Rua Antenor José da Silva',
    'Rua Antônia de Oliveira',
    'Rua Antônio Cândido Alves',
    'Rua Antônio Geraldo Teixeira',
    'Rua Antônio José da Cunha',
    'Rua Antônio Luiz de Oliveira',
    'Rua Antônio Luzia',
    'Rua Antônio Mansur',
    'Rua Antônio Pereira de Almeida',
    'Rua Antônio Pereira',
    'Rua Antônio Queiroz',
    'Rua Aparecida Mendes dos Reis',
    'Rua Aprígio Alves da Cunha',
    'Rua Arara',
    'Rua Ari de Paula Caixeta',
    'Rua Arlindo Guimarães',
    'Rua Artur Botelho',
    'Rua Asa-branca',
    'Rua Ataíde Francisco Peres',
    'Rua Ataíde Nogueira',
    'Rua Baldoíno do Carmo',
    'Rua Baltazar Boaventura',
    'Rua Baltazar Jacob Elias',
    'Rua Beija-Flor',
    'Rua Belo Horizonte',
    'Rua Belvedere',
    'Rua Bem-Te-Vi',
    'Rua Benedito José Esteves',
    'Rua Benedito Santos',
    'Rua Benevides de Novais',
    'Rua Bernardino Machado',
    'Rua Bernardo Guimarães',
    'Rua Bolívia',
    'Rua Brasília',
    'Rua Bulgária',
    'Rua Caetés',
    'Rua Café Arábica',
    'Rua Café Conilon',
    'Rua Café Mundo Novo',
    'Rua Camilo Augusto de Andrade',
    'Rua Canadá',
    'Rua Cândido Dias',
    'Rua Cândido Teixeira de Almeida',
    'Rua Capitão Tarcizo Lopes da Silva',
    'Rua Cardeal',
    'Rua Carlos Ferreira Santos',
    'Rua Carlos Ferreira',
    'Rua Carlos Pereira Carlinhos',
    'Rua Carmem Ferreira da Silva',
    'Rua Casimiro Martins dos Santos',
    'Rua Castro Alves',
    'Rua Catuai',
    'Rua Cecília Maria Cunha',
    'Rua Cecília Péres',
    'Rua Celso Pereira de Queiroz',
    'Rua Cesário Alvim',
    'Rua Chile',
    'Rua Chiquinho Mateus',
    'Rua Cirino Gonçalves da Cunha',
    'Rua Claudino Cristóvão Moreira',
    'Rua Cleide dos Reis Jacinto',
    'Rua Codorna',
    'Rua Coelho Neto',
    'Rua Colômbia',
    'Rua Contorno',
    'Rua Corina Terezinha França Assis',
    'Rua Coronel João Cândido de Aguiar',
    'Rua Coronel Rabelo',
    'Rua Cuba',
    'Rua Custódio Matias Filho',
    'Rua Custódio Rodrigues Vieira',
    'Rua das Acácias',
    'Rua das Azaleias',
    'Rua das Begônias',
    'Rua das Bromélias',
    'Rua das Camélias',
    'Rua das Hortencias',
    'Rua das Orquídeas',
    'Rua das Petúnias',
    'Rua das Rosas',
    'Rua das Tulipas',
    'Rua das Violetas',
    'Rua Demócrito França',
    'Rua Dezesseis',
    'Rua Dickson de Melo',
    'Rua Divino Gonçalves de Oliveira',
    'Rua Divino Martins da Cunha',
    'Rua do Fico',
    'Rua do Império',
    'Rua Dom João VI',
    'Rua Dom Pedro I',
    'Rua Domingos Delfini',
    'Rua Dona Cedilina Carolina do Carmo',
    'Rua Dona Leopoldina',
    'Rua Doralice Afonso de Oliveira',
    'Rua Doralva Afonso da Silva',
    'Rua dos Oitis',
    'Rua Doutor Carlos Eduardo De Oliveira Figueiredo',
    'Rua Doutor Deiró Marra',
    'Rua Doutor Eduardo Lane',
    'Rua Doutor Gustavo Machado',
    'Rua Doutor Hélio Furtado de Oliveira',
    'Rua Doutor Honório de Abreu',
    'Rua Doutor Infante Vieira',
    'Rua Doutor Joaquim Henrique Cardoso',
    'Rua Doutor Napoleão Ferreira Borges',
    'Rua Doutor Silvestre Moreira',
    'Rua Doutor Vicente Soares',
    'Rua Doze de Setembro',
    'Rua Durval Barbosa de Resende',
    'Rua Edgard de Andrade',
    'Rua Edgard Siqueira',
    'Rua Edmar Luís Xavier',
    'Rua Edmundo Coutinho Aguiar',
    'Rua Edson Brasiel',
    'Rua Edson Guimarães Ribeiro',
    'Rua Eduardo Ribeiro',
    'Rua Egito',
    'Rua Elias Alves Cunha',
    'Rua Elmiro Alves do Nascimento',
    'Rua Elmiro Machado',
    'Rua Elpídio Ribeiro da Rocha',
    'Rua Emydio do Espírito Santo',
    'Rua Equador',
    'Rua Ernani Queiroz',
    'Rua Escritor Cândido Martins',
    'Rua Escritor Edgard de Andrade Rocha',
    'Rua Escritor Floriano Peixoto de Paula',
    'Rua Escritor Lázaro Caixeta',
    'Rua Escritor Massilon Machado',
    'Rua Escritor Mauro Chaves',
    'Rua Escritor Michel Wadhy',
    'Rua Escritor Odair Oliveira',
    'Rua Escritor Paulo de Lima',
    'Rua Escritor Paulo Sérgio Martins',
    'Rua Escritor Sebastião Elói dos Santos',
    'Rua Escritora Helena Inez de Melo',
    'Rua Escritora Jussara de Queiroz Mesquita',
    'Rua Escritora Olga Barbosa',
    'Rua Escritora Teodora de Castro Ribeiro',
    'Rua Espanha',
    'Rua Espírito Santo',
    'Rua Estados Unidos',
    'Rua Estevam José Romão',
    'Rua Eurípedes Siqueira Gallego',
    'Rua Evandro Machado de Paula',
    'Rua Expedicionário Amadeu Lacerda',
    'Rua Expedicionário Francisco Caracioli',
    'Rua Expedicionário Francisco Pedro da Silva',
    'Rua Expedito Dias',
    'Rua Ezequias dos Reis',
    'Rua Fio Germano',
    'Rua Flamingo',
    'Rua Flocello Alves',
    'Rua Floriano Alves',
    'Rua Folhados',
    'Rua França',
    'Rua Francisco Alaur Queiroz',
    'Rua Francisco de Paula Arantes',
    'Rua Francisco Firmino de Souza',
    'Rua Francisco José de Almeida',
    'Rua Francisco Ramos',
    'Rua Frederico Lopes Fernandes',
    'Rua Furtado de Menezes',
    'Rua Gabriel Nunes de Paula',
    'Rua Garça',
    'Rua Gavião',
    'Rua Genervino Ferreira Rosa Filho',
    'Rua Gení Barbosa Boaventura',
    'Rua Geralda Afonso de Castro',
    'Rua Geralda Ferreira Alves',
    'Rua Geralda Pereira',
    'Rua Geraldo Alves do Nascimento',
    'Rua Geraldo Calixto',
    'Rua Geraldo Cirino Ramos',
    'Rua Geraldo Eliziário',
    'Rua Geraldo Ferreira Marra',
    'Rua Geraldo Gonçalves',
    'Rua Geraldo José Esteves Pires',
    'Rua Geraldo Martins do Prado',
    'Rua Geraldo Matias de Abreu',
    'Rua Geraldo Santos',
    'Rua Gervásio Marques da Silveira',
    'Rua Gilberto Afonso Vieira',
    'Rua Gildo Guarda',
    'Rua Giselda Castelo Branco dos Santos Soares',
    'Rua Gonçalves Ledo',
    'Rua Governador Valadares, 991',
    'Rua Governador Valadares',
    'Rua Graciano Gonçalves Cunha',
    'Rua Guarani',
    'Rua Helena Florentino de Resende',
    'Rua Hélio Alves de Souza',
    'Rua Heloísa Capuano',
    'Rua Honduras',
    'Rua Humberto Gonçalves Cortes',
    'Rua Hungria',
    'Rua Iaracy Laudino da Silva',
    'Rua Idelfonso José da Silva',
    'Rua Inácio de Oliveira Campos',
    'Rua Independência',
    'Rua Inês Novaes de Oliveira',
    'Rua Inglaterra',
    'Rua Inhambu',
    'Rua Iolanda Teixeira de Freitas',
    'Rua Iracema Maria de Jesus',
    'Rua Iraci',
    'Rua Irineu Afonso',
    'Rua Irmã Adalgisa',
    'Rua Irmã Renée',
    'Rua Irmã Rosângela',
    'Rua Itália',
    'Rua Jacinto Alves Pereira',
    'Rua Jacob Marra',
    'Rua Jair Figueiredo',
    'Rua Januário da Cunha Barbosa',
    'Rua Japão',
    'Rua Jesus Delfino Gomes',
    'Rua João Afonso Português',
    'Rua João Alves de Souza',
    'Rua João Barbosa',
    'Rua João Batista da Mota',
    'Rua João Bernardes da Silveira',
    'Rua João Bernardino da Cunha',
    'Rua João Carlos da Silva',
    'Rua João Carlos dos Reis',
    'Rua João Cobério',
    'Rua João Cunha',
    'Rua João de Carvalho',
    'Rua João Francisco de Souza',
    'Rua João Geraldo de Paula',
    'Rua João Machado Romão',
    'Rua João Moreira Caldeira',
    'Rua João Pereira de Queiroz',
    'Rua João-de-Barro',
    'Rua Joaquim Barbosa Arantes',
    'Rua Joaquim Cardoso Naves',
    'Rua Joaquim Carlos dos Santos',
    'Rua Joaquim Coelho Marra',
    'Rua Joaquim Dornelas',
    'Rua Joaquim Ferreira de Paula',
    'Rua Joaquim Fonseca',
    'Rua Joaquim Luiz da Costa',
    'Rua Joaquim Noé da Fonseca',
    'Rua Joaquim Novato',
    'Rua Joaquim Otávio de Brito',
    'Rua Joel de Souza',
    'Rua Joel Marques de Oliveira',
    'Rua Joel Moreira',
    'Rua Jordelino Augusto de Oliveira',
    'Rua Jorge Fernandes',
    'Rua Jorge Mansur',
    'Rua José Abádio Daura',
    'Rua José Afonso da Cunha',
    'Rua José Araújo',
    'Rua José Bonifácio',
    'Rua José Borges Silveira',
    'Rua José Calixto Jaber',
    'Rua José Clemente Pereira',
    'Rua José de Lourdes de Souza',
    'Rua José Feliciano',
    'Rua José Fernandes Vieira',
    'Rua José Francisco de Santana',
    'Rua José Gonçalves Ribeiro',
    'Rua José Hélio Sebaio',
    'Rua José Honorato Borges',
    'Rua José Jacinto Campos',
    'Rua José Jacinto',
    'Rua José Lemos Borges',
    'Rua José Luiz da Silva',
    'Rua José Mariano da Cunha',
    'Rua José Marques de Moraes',
    'Rua José Martin Gallego',
    'Rua José Nunes Pereira',
    'Rua José Pereira',
    'Rua José Pires de Castro',
    'Rua José Raul Alves do Nascimento',
    'Rua Josefa Afonsina de Melo',
    'Rua Jovino José da Silva',
    'Rua Júlio de Barros',
    'Rua Juriti',
    'Rua Kleber Guarda',
    'Rua Lauri Gonçalves',
    'Rua Lauro Borges Araújo',
    'Rua Lazara Leandra da Cunha',
    'Rua Lázaro Geraldo de Barros',
    'Rua Lázaro Gonçalves',
    'Rua Lázaro Horácio de Paulo',
    'Rua Lázaro Messias Novais',
    'Rua Lenice Cunha Brasiel',
    'Rua Leôncio Batista Cunha',
    'Rua Leonides do Espírito Santo',
    'Rua Leonor de Castro Magalhães',
    'Rua Leontina Vieira da Silva',
    'Rua Levino José da Silva',
    'Rua Liberdade',
    'Rua Lindalva Aparecida Machado',
    'Rua Lindolfo Pereira Guimarães',
    'Rua Lívio Guarda',
    'Rua Lucinda Cunha Ribeiro',
    'Rua Luft',
    'Rua Luis Capuano',
    'Rua Luiz Alberto M de Oliveira',
    'Rua Luxemburgo',
    'Rua Luzia Moysés da Silva',
    'Rua Maestro José Carlos',
    'Rua Major Alvim',
    'Rua Major Tobias Machado',
    'Rua Manaus',
    'Rua Manoel Abobeleira Pego',
    'Rua Manoel Barra da Silva',
    'Rua Manoel Damas',
    'Rua Manoel Pires de Castro',
    'Rua Manoela Marques',
    'Rua Manoelina Aparecida Ferreira',
    'Rua Marechal Floriano',
    'Rua Margarete Moisés',
    'Rua Maria Abadia da Silva Gonçalves',
    'Rua Maria Angélica Pereira da Silva',
    'Rua Maria Augusta de Oliveira',
    'Rua Maria Barbara Pereira',
    'Rua Maria Borges de Rezende Ribeiro',
    'Rua Maria Borges Vieira',
    'Rua Maria Célia de Oliveira',
    'Rua Maria Correia de Queiroz',
    'Rua Maria das Dores Ramos Romão',
    'Rua Maria França de Araújo',
    'Rua Maria Joaquina de Jesus',
    'Rua Maria José de Oliveira Lemos',
    'Rua Maria Marques de Araújo',
    'Rua Maria Marques Silveira',
    'Rua Maria Onofra de Oliveira e Silva',
    'Rua Maria Rosa Luciano',
    'Rua Maria Silva Nunes',
    'Rua Marinha Ferreira da Cunha',
    'Rua Mário Teixeira de Ávila',
    'Rua Martimiano José da Silva',
    'Rua Martins Mundim',
    'Rua Melchiades Inácio de Lima',
    'Rua México',
    'Rua Michio Shimada',
    'Rua Miguel Coelho Marra',
    'Rua Miguel Marques',
    'Rua Modesto Gonçalves',
    'Rua Modesto Teixeira Costa',
    'Rua Monteiro Lobato',
    'Rua Nadim Antônio José Isaac',
    'Rua Natal Cândido Alves',
    'Rua Nazaré Fernandes dos Reis',
    'Rua Nélio de Oliveira e Silva',
    'Rua Nélson Caixeta de Queiroz',
    'Rua Nélson Gonçalves Soares',
    'Rua Nelson Guimarães Queiroz',
    'Rua Neuber Veloso',
    'Rua Nhonhô Arantes',
    'Rua Nhonhô Paiva',
    'Rua Nicanor Valentim',
    'Rua Nonato Matias',
    'Rua Nossa Senhora de Fátima',
    'Rua Odilon Afonso da Silva',
    'Rua Olga de Oliveira Brito',
    'Rua Olímpia Nunes Correia',
    'Rua Olímpio Faustino Alves',
    'Rua Oliveiro José da Silva',
    'Rua Olívia Assis',
    'Rua Onze',
    'Rua Orlando Fernandes Botelho',
    'Rua Osmar Pereira de Queiroz',
    'Rua Osório Afonso da Silva',
    'Rua Oswaldo Pieruccetti',
    'Rua Otávio de Brito',
    'Rua Padre Eustáquio',
    'Rua Padre Jair Machado Gomes',
    'Rua Padre Modesto',
    'Rua Papagaio',
    'Rua Paraguai',
    'Rua Parque das Primaveras',
    'Rua Pastora Cármen Veloso',
    'Rua Patativa',
    'Rua Paulo André Arantes Ribeiro',
    'Rua Pedro Barbosa Victor, 646',
    'Rua Pedro Barbosa Victor',
    'Rua Pedro Basílio de Oliveira',
    'Rua Pedro Gonçalves dos Reis',
    'Rua Pedro Jacinto Filho',
    'Rua Pedro Rodrigues Pereira',
    'Rua Perciliana Gonzaga Pereira',
    'Rua Perequito',
    'Rua Péricles Borges Paiva',
    'Rua Peru',
    'Rua Pintassilgo',
    'Rua Pinto Dias',
    'Rua Planalto de São Paulo',
    'Rua Poeta Lauderico Pio de Souza',
    'Rua Porto Rico',
    'Rua Portugal',
    'Rua Poti',
    'Rua Presidente Vargas',
    'Rua Professor Antônio de Queiroz Cardoso',
    'Rua Professor Cristovam Rangel',
    'Rua Professor Hugo Machado da Silveira',
    'Rua Professor João de Melo',
    'Rua Professor Olímpio dos Santos',
    'Rua Professor Oscar Rodarte',
    'Rua Professora Clérida Borges Alves',
    'Rua Professora Geralda Pereira',
    'Rua Professora Iraídes Barbosa Machado',
    'Rua Professora Januária Tolentino Borges',
    'Rua Prosperidade',
    'Rua Prudência',
    'Rua Quintiliano Alves',
    'Rua Ramiro Gonçalves dos Reis',
    'Rua República do Líbano',
    'Rua Reverendo Roberto Brasileiro',
    'Rua Riacho do Ipiranga',
    'Rua Ricardo Constantino Caldeira',
    'Rua Rio Branco',
    'Rua Rio de Janeiro',
    'Rua Rita Alves de Paula',
    'Rua Rita Martins da Cunha',
    'Rua Roberto Leão',
    'Rua Rodolpho Lemos de Castro',
    'Rua Rogério Leonardo de Oliveira',
    'Rua Romeu Castro Alves',
    'Rua Romeu Malagoli',
    'Rua Ronildo de Jesus Peixoto',
    'Rua Rosa Brandão',
    'Rua Rosa Helena Pereira Alves',
    'Rua Rosalvino de Oliveira',
    'Rua Rubem Fonseca',
    'Rua Sabiá',
    'Rua Salatiel Marques',
    'Rua Salitre',
    'Rua Salvina Barbosa da Silveira',
    'Rua Sanhaçu',
    'Rua São Benedito',
    'Rua São Paulo',
    'Rua Sargento Mário de Moura Caldeira',
    'Rua Saul Gonçalves',
    'Rua Sebastião Alves do Nascimento',
    'Rua Sebastião Fernandes',
    'Rua Sebastião Ferreira do Amaral',
    'Rua Sebastião Ferreira Sales',
    'Rua Sebastião Gonçalves da Cunha',
    'Rua Sebastião Horácio Teixeira',
    'Rua Sebastião José de Paulo',
    'Rua Sebastião Lúcio da Silva',
    'Rua Sebastião Onofre Nunes',
    'Rua Sebastião Queiroz',
    'Rua Sebastião Rogério',
    'Rua Secundino de Faria Tavares',
    'Rua Serenidade',
    'Rua Serra Negra',
    'Rua Sete de Abril',
    'Rua Sílvio Queiroz Siqueira',
    'Rua Sinceridade',
    'Rua Sô Mirote do Nascimento',
    'Rua Sóstenes Santos Souza',
    'Rua Suécia',
    'Rua Suíça',
    'Rua Tadão Nobuyasu',
    'Rua Tadeu Pereira Guimarães',
    'Rua Tapajós',
    'Rua Teodora Maria de Queiroz',
    'Rua Teodoro Gonçalves',
    'Rua Thiago Rezende Malagoli',
    'Rua Tico-Tico',
    'Rua Tocantins',
    'Rua Tucano',
    'Rua Tupi',
    'Rua Ubaldino Silva',
    'Rua Ubirajara',
    'Rua Uirapuru',
    'Rua Uruguai',
    'Rua Valdemira Sérgia Soares',
    'Rua Valdomiro Cardoso',
    'Rua Valmira Silva Souza',
    'Rua Valter Teixeira de Ávila',
    'Rua Vanderlim Valter Novais Filho',
    'Rua Vereador Joaquim Assis Filho',
    'Rua Vereadora Ismene Mendes',
    'Rua Vicente Caldeira',
    'Rua Vicente de Paula Caixeta',
    'Rua Vicente Esteves dos Reis',
    'Rua Vicente Pereira Bragança',
    'Rua Vinte Um de Abril',
    'Rua Virmondes Bomtempo de Oliveira',
    'Rua Virtudes',
    'Rua Vitória',
    'Rua Wadhy Miguel Felipe',
    'Rua Xingu',
    'Rua Zaina Aparecida Marques de Oliveira',
    'Rua Zequinha Silvestre',
    'Rua Zinna Caixeta',
    'Rua Zoroastro da Mota Machado',
    'Travessa Macaúbas',
]
